/**
 * OpenAPI codegen smoke — tasks 1.37 + 1.38.
 *
 * Confirms the two generated `.d.ts` files exist, contain the schema
 * names we expect from the respective YAML specs, and that the
 * public re-exports (`CoreAPI*` / `BrainAPI*`) are usable at compile
 * time.
 *
 * Drift between the committed generated files and what
 * openapi-typescript would produce right now is enforced by the root's
 * `npm run generate:check` CI gate (task 1.41) — not here, since
 * spawning the codegen inside jest would duplicate CI work and slow
 * the suite.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import type {
  CoreAPIComponents,
  CoreAPIPaths,
  BrainAPIComponents,
  BrainAPIPaths,
} from '../src';

const genDir = path.join(__dirname, '..', 'src', 'gen');
const corePath = path.join(genDir, 'core-api.d.ts');
const brainPath = path.join(genDir, 'brain-api.d.ts');

describe('OpenAPI codegen — core-api.d.ts (task 1.37)', () => {
  it('generated file exists on disk', () => {
    expect(fs.existsSync(corePath)).toBe(true);
  });

  it('contains the expected top-level openapi-typescript exports', () => {
    const body = fs.readFileSync(corePath, 'utf8');
    // openapi-typescript emits `paths` + `components` as interfaces
    // when the spec has any paths / schemas; `operations` comes out
    // as `interface` when the spec uses `operationId`, or as
    // `type operations = Record<string, never>` when it doesn't —
    // core-api doesn't currently use operationIds, so accept either.
    expect(body).toMatch(/export interface paths\b/);
    expect(body).toMatch(/export interface components\b/);
    expect(body).toMatch(/export (interface|type) operations\b/);
  });

  it('contains schema shapes the Core↔Brain contract depends on', () => {
    const body = fs.readFileSync(corePath, 'utf8');
    for (const name of ['HealthResponse', 'VaultStoreRequest', 'ReasonResult']) {
      expect(body).toContain(`${name}:`);
    }
  });

  it('starts with the auto-generated banner (file-provenance marker)', () => {
    const body = fs.readFileSync(corePath, 'utf8');
    expect(body.slice(0, 200)).toContain('auto-generated by openapi-typescript');
  });

  it('re-exports compile as type-only (CoreAPIPaths / CoreAPIComponents reachable)', () => {
    const _paths: CoreAPIPaths = {} as CoreAPIPaths;
    const _components: CoreAPIComponents = {} as CoreAPIComponents;
    void _paths;
    void _components;
    type HealthResponse = CoreAPIComponents['schemas']['HealthResponse'];
    const h: HealthResponse = { status: 'ok' };
    expect(h.status).toBe('ok');
  });
});

describe('OpenAPI codegen — brain-api.d.ts (task 1.38)', () => {
  it('generated file exists on disk', () => {
    expect(fs.existsSync(brainPath)).toBe(true);
  });

  it('contains the expected top-level openapi-typescript exports', () => {
    const body = fs.readFileSync(brainPath, 'utf8');
    // brain-api DOES use operationIds (e.g. `process_event_v1_process_post`)
    // so `operations` is always an interface here — stricter than core-api's
    // tolerant regex. Catches spec-authors accidentally dropping operationIds.
    expect(body).toMatch(/export interface paths\b/);
    expect(body).toMatch(/export interface components\b/);
    expect(body).toMatch(/export interface operations\b/);
  });

  it('contains event-variant schemas the Brain process endpoint expects', () => {
    const body = fs.readFileSync(brainPath, 'utf8');
    // Spot-check a few of the typed event variants. If `agent_intent`,
    // `vault_unlocked`, etc. disappear from the spec, the Brain process
    // endpoint's `oneOf` contract degrades silently — this test fires
    // before that reaches a deployed service.
    for (const name of ['AgentIntentEvent', 'ApprovalNeededEvent', 'ReasonRequest']) {
      expect(body).toContain(`${name}:`);
    }
  });

  it('starts with the auto-generated banner (file-provenance marker)', () => {
    const body = fs.readFileSync(brainPath, 'utf8');
    expect(body.slice(0, 200)).toContain('auto-generated by openapi-typescript');
  });

  it('re-exports compile as type-only (BrainAPIPaths / BrainAPIComponents reachable)', () => {
    const _paths: BrainAPIPaths = {} as BrainAPIPaths;
    const _components: BrainAPIComponents = {} as BrainAPIComponents;
    void _paths;
    void _components;
    // Narrow one event schema to prove indexing works across brain's
    // much wider schema set.
    type AgentIntent = BrainAPIComponents['schemas']['AgentIntentEvent'];
    const e: AgentIntent = {} as AgentIntent;
    expect(e).toBeDefined();
  });
});
