/**
 * Group coordination (docs/GROUP_COORDINATION_ARCHITECTURE.md): the organizer's
 * fold over N 1:1 `availability_coordination` spokes, and the owner-private
 * plan that remembers them.
 */
export {
  foldGroupPlan,
  isMeetingSlot,
  slotKey,
  type FoldGuest,
  type FoldResult,
  type FoldState,
  type MeetingSlot,
  type SpokeReply,
} from './group_fold';
export {
  DEFAULT_WINDOW_SECONDS,
  DISCLOSURE_KINDS,
  MAX_DISCLOSURE_CHARS,
  MAX_GROUP_GUESTS,
  MAX_INTENT_CHARS,
  MAX_PLAN_CANDIDATES,
  MAX_PLAN_ROUNDS,
  MAX_WINDOW_SECONDS,
  abandon,
  choose,
  createGroupPlan,
  currentSpoke,
  deriveRequirements,
  foldPlan,
  makeOptional,
  markUnreachable,
  normaliseDisclosure,
  openRound,
  recordReply,
  recordSpoke,
  widen,
  windowClosesAt,
  type Disclosure,
  type DisclosureKind,
  type GroupPlan,
  type GroupPlanRefusal,
  type GroupPlanState,
  type GuestRecord,
  type PlanResult,
  type Requirement,
  type SpokeInput,
  type SpokeOutcome,
  type SpokeRecord,
} from './group_plan';
export {
  GROUP_COORDINATION_CAPABILITY,
  abandonPlan,
  chooseSlot,
  deleteGroupPlan,
  listGroupPlanHandles,
  listGroupPlans,
  makeGuestOptional,
  openGroupPlan,
  readGroupPlan,
  replayOfferForOpenPlans,
  spokeParams,
  toSpokeReply,
  widenPlan,
  wireGroupCoordinationOfferReplay,
  type GroupCoordinationDeps,
  type GroupCoordinationRefusal,
  type GroupCoordinationResult,
  type OpenGroupPlanInput,
} from './group_coordination_service';
export {
  InMemoryGroupPlanRepository,
  SQLiteGroupPlanRepository,
  getGroupPlanRepository,
  rehydrateGroupPlan,
  setGroupPlanRepository,
  type GroupPlanRepository,
} from './group_plan_repository';
export {
  DISCLOSURE_REVIEW_APPROVAL_TYPE,
  coordinationWorkflowHooks,
  disclosureCategory,
  gateDisclosures,
  makeDisclosureDecisionHandler,
  makeDisclosureEgressGate,
  parseDisclosureReviewPayload,
  reviewTaskIdFor,
  tierAdmitsDisclosure,
  type DisclosureGateDeps,
  type DisclosureReviewPayload,
  type GatedDisclosures,
} from './disclosure_egress';
export {
  projectHandle,
  projectPlan,
  readGroupPlanHandles,
  readGroupPlanWire,
  type GroupPlanFoldWire,
  type GroupPlanGuestWire,
  type GroupPlanHandleWire,
  type GroupPlanWire,
} from './plan_wire';
