#!/usr/bin/env bash
# publish_cli.sh — gated PyPI publish for dina-agent.
#
# Enforces the version↔content binding before anything leaves the machine:
#   1. cli/ working tree must be clean (publish what's committed).
#   2. cli/.release binding must be valid at HEAD (content ↔ version ↔
#      pyproject all agree — same check as the pre-commit hook).
#   3. The version must not already exist on PyPI (uploads are immutable).
# Then bakes the tree digest into the wheel (_build.py), builds, smoke-tests
# the wheel in a scratch venv, uploads, and verifies PyPI serves it.
#
# Usage: scripts/release/publish_cli.sh [--dry-run]

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"
CVS="$REPO_ROOT/scripts/release/component_version.sh"
DRY="${1:-}"

# ── Gate 1: clean tree ──
if [ -n "$(git status --porcelain -- cli/)" ]; then
    echo "✗ cli/ working tree is dirty — commit first; publish ships committed code only." >&2
    git status --short -- cli/ >&2
    exit 1
fi

# ── Gate 2: binding valid at HEAD ──
"$CVS" check cli --head

read -r VERSION TREE _ <<< "$("$CVS" stamp cli)"
echo "▸ publishing dina-agent $VERSION (tree $TREE)"

# ── Gate 3: version not already on PyPI ──
if curl -fsS "https://pypi.org/pypi/dina-agent/$VERSION/json" >/dev/null 2>&1; then
    echo "✗ dina-agent $VERSION already exists on PyPI — bump the version (uploads are immutable)." >&2
    exit 1
fi

# ── Bake the tree digest into the wheel ──
BUILD_PY="cli/src/dina_cli/_build.py"
cleanup() { rm -f "$BUILD_PY"; }
trap cleanup EXIT
printf '# generated by scripts/release/publish_cli.sh — do not commit\nTREE = "%s"\n' "$TREE" > "$BUILD_PY"

# ── Build ──
cd cli
rm -rf dist build
python3 -m build

# ── Smoke-test the wheel in a scratch venv ──
SMOKE="$(mktemp -d)/venv"
python3 -m venv "$SMOKE"
"$SMOKE/bin/pip" install -q "dist/dina_agent-$VERSION-py3-none-any.whl"
OUT="$("$SMOKE/bin/dina" --version)"
echo "▸ wheel smoke: $OUT"
case "$OUT" in
    *"$VERSION"*"$TREE"*) : ;;
    *) echo "✗ wheel version/tree mismatch: expected $VERSION + $TREE in: $OUT" >&2; exit 1 ;;
esac

if [ "$DRY" = "--dry-run" ]; then
    echo "▸ dry run — skipping upload. Artifacts in cli/dist/."
    exit 0
fi

# ── Upload + verify ──
python3 -m twine upload --non-interactive "dist/dina_agent-$VERSION.tar.gz" "dist/dina_agent-$VERSION-py3-none-any.whl"
echo "▸ uploaded. Verifying PyPI serves $VERSION..."
for i in 1 2 3 4 5 6; do
    if curl -fsS "https://pypi.org/pypi/dina-agent/$VERSION/json" >/dev/null 2>&1; then
        echo "✓ dina-agent $VERSION live on PyPI (tree $TREE)"
        exit 0
    fi
    sleep 10
done
echo "⚠ upload succeeded but the PyPI JSON API has not caught up yet — check https://pypi.org/project/dina-agent/$VERSION/" >&2
