/**
 * Mint the static repo-proof SELF-CHECK fixture (RESEARCHER_KERNEL §5.C1):
 * one signed AT-Protocol repo holding one plugin release, produced through the
 * audited library's own write path with a FIXED secp256k1 key. The record's
 * rkey and CID are stable (content-addressed); the commit's `rev` is a TID of
 * the minting moment, so a re-run yields a different but equally valid
 * fixture. The output is `src/repo_proof_fixture.ts`.
 *
 * The key is a test key with no authority anywhere: the DID is fictitious and
 * its document is served only by the self-check's own resolver. What the
 * fixture proves is that the chain — CAR read, commit signature, MST walk,
 * rkey = f(cid) — RUNS on the host that evaluates it (Hermes, a browser, Node).
 *
 *   node packages/home-node/scripts/mint_repo_proof_fixture.mjs
 */

import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { Secp256k1Keypair } from '@atproto/crypto';
import { blocksToCarFile, MemoryBlockstore, Repo, WriteOpAction } from '@atproto/repo';

// `@dina/protocol` is TypeScript source; its CommonJS build carries the rkey
// rule (`npm run build` in packages/protocol if this import fails).
const require = createRequire(import.meta.url);
const { releaseRkeyFromCid } = require('../../protocol/dist/plugins/release_rkey.js');

const COLLECTION = 'com.dinakernel.plugin.release';
const DID = 'did:plc:dinaselfcheckfixture0000';
const RECORD = {
  $type: COLLECTION,
  plugin_id: 'com.dinakernel.selfcheck',
  version: '1.0.0',
  display_name: 'Repo-proof self-check fixture',
  execution: { mode: 'interpreted' },
  capabilities: [],
};
// Fixed test key: 32 bytes, 0x11 repeated. No authority, never reused.
const PRIVATE_KEY = new Uint8Array(32).fill(0x11);

async function mint() {
  const keypair = await Secp256k1Keypair.import(PRIVATE_KEY);
  // The rkey is the record's content address, so mint once to learn the CID,
  // then mint the repo that stores the record AT that rkey.
  const probe = await Repo.create(new MemoryBlockstore(), DID, keypair, [
    { action: WriteOpAction.Create, collection: COLLECTION, rkey: '3jzfcijpj2z2a', record: RECORD },
  ]);
  const probeCid = await probe.data.get(`${COLLECTION}/3jzfcijpj2z2a`);
  const rkey = releaseRkeyFromCid(probeCid.toString());
  if (rkey === null) throw new Error('unexpected CID shape');
  const storage = new MemoryBlockstore();
  const repo = await Repo.create(storage, DID, keypair, [
    { action: WriteOpAction.Create, collection: COLLECTION, rkey, record: RECORD },
  ]);
  const cid = await repo.data.get(`${COLLECTION}/${rkey}`);
  const car = await blocksToCarFile(repo.cid, storage.blocks);
  return { rkey, cid: cid.toString(), car, signingKey: keypair.did().replace(/^did:key:/, '') };
}

const { rkey, cid, car, signingKey } = await mint();
const hex = Array.from(car, (b) => b.toString(16).padStart(2, '0')).join('');
const out = `/**
 * GENERATED by scripts/mint_repo_proof_fixture.mjs — do not edit by hand.
 *
 * The repo-proof self-check fixture (§5.C1): a signed repo holding one plugin
 * release, minted through \`@atproto/repo\` with a fixed test key. Served only by
 * the self-check's own resolver and fetch; the DID has no authority anywhere.
 */

export const REPO_PROOF_FIXTURE = {
  did: '${DID}',
  collection: '${COLLECTION}',
  rkey: '${rkey}',
  cid: '${cid}',
  signingKey: '${signingKey}',
  pds: 'https://selfcheck.invalid',
  record: ${JSON.stringify(RECORD)},
  carHex:
    '${hex}',
} as const;
`;
const here = dirname(fileURLToPath(import.meta.url));
writeFileSync(join(here, '..', 'src', 'repo_proof_fixture.ts'), out);
console.log(`fixture: rkey=${rkey} cid=${cid} car=${car.length} bytes`);
