#!/usr/bin/env bash
# install_appview.sh — One-command Trust AppView setup
#
# Usage:
#   ./install_appview.sh              # first-time setup
#   ./install_appview.sh --skip-build # skip Docker build (use existing images)
#
# What it does:
#   1. Checks prerequisites (docker, docker compose, node, npm)
#   2. Installs Node.js dependencies
#   3. Creates .env if missing (with default Postgres password)
#   4. Starts PostgreSQL 17 + Jetstream via Docker Compose
#   5. Waits for Postgres health check
#   6. Pushes schema (27 tables, 97 indexes) via Drizzle Kit
#   7. Displays status and endpoints
#
# Idempotent: safe to re-run. Schema push is additive (no data loss).

set -euo pipefail

APPVIEW_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="${APPVIEW_DIR}/.env"
HEALTH_TIMEOUT=60
HEALTH_INTERVAL=3
SKIP_BUILD=false

for arg in "$@"; do
    case "$arg" in
        --skip-build) SKIP_BUILD=true ;;
    esac
done

# ---------------------------------------------------------------------------
# Colors
# ---------------------------------------------------------------------------

if [ -t 1 ]; then
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    RED='\033[0;31m'
    CYAN='\033[0;36m'
    BOLD='\033[1m'
    DIM='\033[2m'
    RESET='\033[0m'
else
    GREEN='' YELLOW='' RED='' CYAN='' BOLD='' DIM='' RESET=''
fi

ok()   { echo -e "  ${GREEN}[ok]${RESET}   $1"; }
skip() { echo -e "  ${DIM}[skip]${RESET} $1"; }
fail() { echo -e "  ${RED}[fail]${RESET} $1" >&2; exit 1; }
warn() { echo -e "  ${YELLOW}[warn]${RESET} $1"; }
info() { echo -e "  ${DIM}[....]${RESET} $1"; }

# ---------------------------------------------------------------------------
# Banner
# ---------------------------------------------------------------------------

echo ""
echo -e "${BOLD}╔══════════════════════════════════════╗${RESET}"
echo -e "${BOLD}║     Dina Trust AppView Setup    ║${RESET}"
echo -e "${BOLD}╚══════════════════════════════════════╝${RESET}"
echo ""
echo -e "  Directory: ${CYAN}${APPVIEW_DIR}${RESET}"
echo ""

# ---------------------------------------------------------------------------
# Step 1: Prerequisites
# ---------------------------------------------------------------------------

echo -e "${BOLD}Step 1: Checking prerequisites${RESET}"

command -v docker >/dev/null 2>&1 || fail "Docker is not installed. Install from https://docs.docker.com/get-docker/"
ok "Docker found"

if docker compose version >/dev/null 2>&1; then
    COMPOSE="docker compose"
    ok "Docker Compose found (plugin)"
elif command -v docker-compose >/dev/null 2>&1; then
    COMPOSE="docker-compose"
    ok "Docker Compose found (standalone)"
else
    fail "Docker Compose not found. Install from https://docs.docker.com/compose/install/"
fi

command -v node >/dev/null 2>&1 || fail "Node.js is not installed. Install from https://nodejs.org/"
ok "Node.js found ($(node --version))"

command -v npm >/dev/null 2>&1 || fail "npm is not installed."
ok "npm found"

docker info >/dev/null 2>&1 || fail "Docker daemon is not running. Start Docker and try again."
ok "Docker daemon running"

echo ""

# ---------------------------------------------------------------------------
# Step 2: Install dependencies
# ---------------------------------------------------------------------------

echo -e "${BOLD}Step 2: Installing Node.js dependencies${RESET}"

cd "${APPVIEW_DIR}"

if [ -d "node_modules" ] && [ -f "node_modules/.package-lock.json" ]; then
    skip "node_modules already exists"
else
    npm install --loglevel=warn 2>&1 | tail -3
    ok "Dependencies installed"
fi

echo ""

# ---------------------------------------------------------------------------
# Step 3: Create .env
# ---------------------------------------------------------------------------

echo -e "${BOLD}Step 3: Configuring environment${RESET}"

if [ ! -f "${ENV_FILE}" ]; then
    POSTGRES_PASSWORD=$(openssl rand -hex 16 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(16), end='')")

    cat > "${ENV_FILE}" << ENVEOF
# AppView Configuration
# Generated by install_appview.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://dina:${POSTGRES_PASSWORD}@localhost:5432/dina_trust
JETSTREAM_URL=ws://localhost:6008
LOG_LEVEL=info
PORT=3000
ENVEOF

    chmod 600 "${ENV_FILE}"
    ok "Created .env (mode 600)"
else
    skip ".env already exists"
    # Source existing env for POSTGRES_PASSWORD
    POSTGRES_PASSWORD=$(sed -n 's/^POSTGRES_PASSWORD=\(.*\)$/\1/p' "${ENV_FILE}" 2>/dev/null || true)
fi

echo ""

# ---------------------------------------------------------------------------
# Step 4: Start Docker containers
# ---------------------------------------------------------------------------

echo -e "${BOLD}Step 4: Starting PostgreSQL + Jetstream${RESET}"

if [ "${SKIP_BUILD}" = true ]; then
    $COMPOSE up -d postgres jetstream 2>&1 | while IFS= read -r line; do
        echo -e "  ${DIM}${line}${RESET}"
    done
else
    $COMPOSE up -d --build postgres jetstream 2>&1 | while IFS= read -r line; do
        echo -e "  ${DIM}${line}${RESET}"
    done
fi

ok "Containers started"
echo ""

# ---------------------------------------------------------------------------
# Step 5: Wait for Postgres
# ---------------------------------------------------------------------------

echo -e "${BOLD}Step 5: Waiting for PostgreSQL health check${RESET}"

ELAPSED=0
while [ $ELAPSED -lt $HEALTH_TIMEOUT ]; do
    if docker compose exec -T postgres pg_isready -U dina -d dina_trust >/dev/null 2>&1; then
        ok "PostgreSQL is healthy"
        break
    fi

    printf "  ${DIM}[....]${RESET} Waiting... (%ds/%ds)\r" "$ELAPSED" "$HEALTH_TIMEOUT"
    sleep $HEALTH_INTERVAL
    ELAPSED=$((ELAPSED + HEALTH_INTERVAL))
done

if [ $ELAPSED -ge $HEALTH_TIMEOUT ]; then
    fail "PostgreSQL health check timed out after ${HEALTH_TIMEOUT}s. Check logs: ${COMPOSE} logs postgres"
fi

echo ""

# ---------------------------------------------------------------------------
# Step 6: Push schema
# ---------------------------------------------------------------------------

echo -e "${BOLD}Step 6: Pushing database schema${RESET}"

info "Pushing 27 tables with 97 indexes via Drizzle Kit..."
npx drizzle-kit push 2>&1 | while IFS= read -r line; do
    case "$line" in
        *"Changes applied"*) echo -e "  ${GREEN}${line}${RESET}" ;;
        *"Warning"*|*"warning"*) echo -e "  ${YELLOW}${line}${RESET}" ;;
        *) ;;
    esac
done

ok "Schema pushed"
echo ""

# ---------------------------------------------------------------------------
# Step 7: Start application containers (optional)
# ---------------------------------------------------------------------------

echo -e "${BOLD}Step 7: Starting application containers${RESET}"

if [ "${SKIP_BUILD}" = true ]; then
    skip "Skipped (--skip-build). Start manually: ${COMPOSE} up -d"
else
    $COMPOSE up -d 2>&1 | while IFS= read -r line; do
        echo -e "  ${DIM}${line}${RESET}"
    done
    ok "All containers started"
fi

echo ""

# ---------------------------------------------------------------------------
# Final banner
# ---------------------------------------------------------------------------

# Count tables
TABLE_COUNT=$(docker compose exec -T postgres psql -U dina -d dina_trust -t -c \
    "SELECT count(*) FROM information_schema.tables WHERE table_schema='public'" 2>/dev/null | tr -d ' ' || echo "?")

echo -e "${BOLD}╔══════════════════════════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}║            Trust AppView is Live!                      ║${RESET}"
echo -e "${BOLD}╚══════════════════════════════════════════════════════════════╝${RESET}"
echo ""
echo -e "  ${BOLD}Database:${RESET}  ${TABLE_COUNT} tables in dina_trust"
echo ""
echo -e "  ${BOLD}Services:${RESET}"
echo -e "    PostgreSQL: ${CYAN}localhost:5432${RESET}"
echo -e "    Jetstream:  ${CYAN}localhost:6008${RESET}"
echo -e "    Web API:    ${CYAN}http://localhost:3000${RESET}"
echo ""
echo -e "  ${BOLD}Commands:${RESET}"
echo -e "    Logs:    ${CYAN}${COMPOSE} logs -f${RESET}"
echo -e "    Stop:    ${CYAN}${COMPOSE} down${RESET}"
echo -e "    Tests:   ${CYAN}npx vitest run${RESET}"
echo ""
