"""Port interfaces for PII scrubbing and the Entity Vault pattern.

Matches Brain TEST_PLAN SS3 (PII Scrubber) and the contracts in
``brain/tests/contracts.py::PIIScrubber`` / ``EntityVault``.

INVARIANT: PII scrubbing is ALWAYS local (Go regex Tier 1 + Python
Presidio/spaCy Tier 2).  It NEVER routes unscrubbed text to a cloud
LLM.  This is a hard security gate, not a preference (Architecture SS11).
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class PIIScrubber(Protocol):
    """Combined Tier 1 (regex) + Tier 2 (Presidio NER) PII scrubbing.

    Tier 1 runs first (via core's ``POST /v1/pii/scrub``), replacing
    emails, phones, SSNs, and credit-card numbers with deterministic
    tokens (``[EMAIL_1]``, ``[PHONE_1]``, ...).

    Tier 2 then processes the already-tokenised text through Presidio
    (wrapping spaCy ``en_core_web_sm``) to catch named entities
    (PERSON, ORG, LOC) that regex cannot detect.

    SAFE entities (DATE, TIME, MONEY, PERCENT, NORP, etc.) are never
    scrubbed — they are essential for LLM reasoning.

    Both tiers share a single replacement map so tokens are globally
    unique and sequentially numbered per type.
    """

    def scrub(self, text: str) -> tuple[str, list[dict]]:
        """Scrub PII from *text*.

        Returns:
            A 2-tuple of ``(scrubbed_text, entities)`` where *entities*
            is a list of dicts each containing ``type``, ``value``, and
            ``token`` keys.
        """
        ...

    def detect(self, text: str) -> list[dict]:
        """Detect PII entities in *text* without replacing them.

        Returns:
            List of entity dicts with ``type`` and ``value`` keys.
        """
        ...

    def rehydrate(self, text: str, entity_map: list[dict]) -> str:
        """Replace tokens in *text* with original values from entity_map.

        Returns:
            Text with tokens replaced by originals.
        """
        ...


@runtime_checkable
class EntityVault(Protocol):
    """Ephemeral in-memory replacement map for the Entity Vault pattern.

    Created per-request when routing to a cloud LLM.  Skipped entirely
    when using a local LLM (PII never leaves the Home Node).

    Lifecycle:
        1. ``create()``      — build the vault from scrubbing output.
        2. Send scrubbed text to cloud LLM.
        3. ``rehydrate()``   — replace tokens in LLM response.
        4. ``destroy()``     — clear the dict; vault must not outlive request.

    The vault is NEVER persisted to disk, NEVER logged, and NEVER stored
    in the main encrypted vault (``identity.sqlite``).
    """

    def create(self, entities: list[dict]) -> dict:
        """Build an in-memory replacement map from detected entities.

        Parameters:
            entities: List of entity dicts with ``token`` and ``value`` keys.

        Returns:
            A plain dict mapping tokens to original values, e.g.
            ``{"[PERSON_1]": "Dr. Sharma", "[ORG_1]": "Apollo Hospital"}``.
        """
        ...

    def rehydrate(self, text: str, vault: dict) -> str:
        """Replace tokens in *text* with original values from *vault*.

        Only tokens that exist as keys in *vault* are replaced.  Tokens
        coincidentally generated by the LLM are NOT rehydrated (a unique
        prefix/format may be used to disambiguate).
        """
        ...

    def destroy(self, vault: dict) -> None:
        """Destroy the vault by clearing its contents.

        After this call the dict is empty and all references to original
        PII values are gone.  The caller should also ``del`` the
        reference so the GC can collect the object.
        """
        ...
