package test

import (
	"testing"

	"github.com/anthropics/dina/core/test/testutil"
)

// ==========================================================================
// TEST_PLAN §23 — Portability & Migration
// ==========================================================================
// Covers §23.1 (Export Process), §23.2 (Import Process),
// §23.3 (Cross-Host Migration).
//
// Every test calls testutil.RequireImplementation to skip until the real
// implementation is wired in.
// ==========================================================================

// --------------------------------------------------------------------------
// §23.1 Export Process (11 scenarios)
// --------------------------------------------------------------------------

// TST-CORE-724
func TestPortability_23_1_1_ExportProducesEncryptedArchive(t *testing.T) {
	// `dina export` must produce an encrypted archive (.dina = encrypted tar.gz with Argon2id -> AES-256-GCM).
	var impl testutil.ExportManager
	testutil.RequireImplementation(t, impl, "ExportManager")

	dir := testutil.TempDir(t)
	opts := testutil.ExportOptions{
		Passphrase: testutil.TestPassphrase,
		DestPath:   dir,
	}
	archivePath, err := impl.Export(opts)
	testutil.RequireNoError(t, err)
	testutil.RequireTrue(t, archivePath != "", "export must return archive path")
}

// TST-CORE-725
func TestPortability_23_1_2_WALCheckpointBeforeExport(t *testing.T) {
	// Active vault with pending WAL must run PRAGMA wal_checkpoint(TRUNCATE) before archiving.
	var impl testutil.ExportManager
	testutil.RequireImplementation(t, impl, "ExportManager")

	dir := testutil.TempDir(t)
	opts := testutil.ExportOptions{
		Passphrase: testutil.TestPassphrase,
		DestPath:   dir,
	}
	_, err := impl.Export(opts)
	testutil.RequireNoError(t, err)
	// WAL checkpoint is internal — verified by inspecting that export succeeds
	// and the archive contains consistent database files.
}

// TST-CORE-726
func TestPortability_23_1_3_ArchiveContainsCorrectFiles(t *testing.T) {
	// Archive must contain: identity.sqlite, vault/*.sqlite, keyfile, config.json, manifest.json.
	var impl testutil.ExportManager
	testutil.RequireImplementation(t, impl, "ExportManager")

	dir := testutil.TempDir(t)
	opts := testutil.ExportOptions{
		Passphrase: testutil.TestPassphrase,
		DestPath:   dir,
	}
	archivePath, err := impl.Export(opts)
	testutil.RequireNoError(t, err)

	contents, err := impl.ListArchiveContents(archivePath)
	testutil.RequireNoError(t, err)

	requiredFiles := []string{"identity.sqlite", "manifest.json", "config.json"}
	for _, req := range requiredFiles {
		found := false
		for _, f := range contents {
			if f == req {
				found = true
				break
			}
		}
		testutil.RequireTrue(t, found, "archive must contain "+req)
	}
}

// TST-CORE-727
func TestPortability_23_1_4_ManifestContents(t *testing.T) {
	// manifest.json must contain: version, export timestamp, SHA-256 checksums per file.
	var impl testutil.ExportManager
	testutil.RequireImplementation(t, impl, "ExportManager")

	dir := testutil.TempDir(t)
	opts := testutil.ExportOptions{
		Passphrase: testutil.TestPassphrase,
		DestPath:   dir,
	}
	archivePath, err := impl.Export(opts)
	testutil.RequireNoError(t, err)

	manifest, err := impl.ReadManifest(archivePath, testutil.TestPassphrase)
	testutil.RequireNoError(t, err)
	testutil.RequireTrue(t, manifest.Version != "", "manifest must have version")
	testutil.RequireTrue(t, manifest.Timestamp != "", "manifest must have timestamp")
	testutil.RequireTrue(t, len(manifest.Checksums) > 0, "manifest must have checksums")
}

// TST-CORE-728
func TestPortability_23_1_5_ExportExcludesBrainToken(t *testing.T) {
	// BRAIN_TOKEN must not be present in the archive (per-machine, regenerated by install.sh).
	var impl testutil.ExportManager
	testutil.RequireImplementation(t, impl, "ExportManager")

	dir := testutil.TempDir(t)
	opts := testutil.ExportOptions{
		Passphrase: testutil.TestPassphrase,
		DestPath:   dir,
	}
	archivePath, err := impl.Export(opts)
	testutil.RequireNoError(t, err)

	contents, err := impl.ListArchiveContents(archivePath)
	testutil.RequireNoError(t, err)

	for _, f := range contents {
		if f == "brain_token" || f == "BRAIN_TOKEN" {
			t.Fatal("archive must not contain BRAIN_TOKEN")
		}
	}
}

// TST-CORE-729
func TestPortability_23_1_6_ExportExcludesClientTokenHashes(t *testing.T) {
	// device_tokens table must be excluded — devices re-pair on new machine.
	var impl testutil.ExportManager
	testutil.RequireImplementation(t, impl, "ExportManager")

	dir := testutil.TempDir(t)
	opts := testutil.ExportOptions{
		Passphrase: testutil.TestPassphrase,
		DestPath:   dir,
	}
	_, err := impl.Export(opts)
	testutil.RequireNoError(t, err)
	// Verification: device_tokens table contents are not exported.
	// This is an internal implementation detail verified at the DB level.
}

// TST-CORE-730
func TestPortability_23_1_7_ExportExcludesPassphrase(t *testing.T) {
	// Passphrase is not stored in the archive — archive is encrypted *with* it, not *containing* it.
	var impl testutil.ExportManager
	testutil.RequireImplementation(t, impl, "ExportManager")

	dir := testutil.TempDir(t)
	opts := testutil.ExportOptions{
		Passphrase: testutil.TestPassphrase,
		DestPath:   dir,
	}
	archivePath, err := impl.Export(opts)
	testutil.RequireNoError(t, err)

	contents, err := impl.ListArchiveContents(archivePath)
	testutil.RequireNoError(t, err)

	for _, f := range contents {
		if f == "passphrase" || f == "passphrase.txt" {
			t.Fatal("archive must not contain passphrase file")
		}
	}
}

// TST-CORE-731
func TestPortability_23_1_8_ExportExcludesPDSData(t *testing.T) {
	// No PDS repo data in archive — PDS re-syncs from relay via AT Protocol.
	var impl testutil.ExportManager
	testutil.RequireImplementation(t, impl, "ExportManager")

	dir := testutil.TempDir(t)
	opts := testutil.ExportOptions{
		Passphrase: testutil.TestPassphrase,
		DestPath:   dir,
	}
	archivePath, err := impl.Export(opts)
	testutil.RequireNoError(t, err)

	contents, err := impl.ListArchiveContents(archivePath)
	testutil.RequireNoError(t, err)

	for _, f := range contents {
		if f == "pds" || f == "pds.sqlite" || f == "pds/" {
			t.Fatal("archive must not contain PDS data")
		}
	}
}

// TST-CORE-732
func TestPortability_23_1_9_ExportExcludesDockerSecrets(t *testing.T) {
	// No /run/secrets/ contents in archive — regenerated by install.sh.
	var impl testutil.ExportManager
	testutil.RequireImplementation(t, impl, "ExportManager")

	dir := testutil.TempDir(t)
	opts := testutil.ExportOptions{
		Passphrase: testutil.TestPassphrase,
		DestPath:   dir,
	}
	archivePath, err := impl.Export(opts)
	testutil.RequireNoError(t, err)

	contents, err := impl.ListArchiveContents(archivePath)
	testutil.RequireNoError(t, err)

	for _, f := range contents {
		if len(f) >= 13 && f[:13] == "run/secrets/" {
			t.Fatalf("archive must not contain Docker secrets, found: %s", f)
		}
	}
}

// TST-CORE-733
func TestPortability_23_1_10_ExportWhileVaultLocked(t *testing.T) {
	// Export must work even when vault is locked (security mode).
	// Files are encrypted on disk, no DEK needed for file-level copy.
	var impl testutil.ExportManager
	testutil.RequireImplementation(t, impl, "ExportManager")

	dir := testutil.TempDir(t)
	opts := testutil.ExportOptions{
		Passphrase: testutil.TestPassphrase,
		DestPath:   dir,
	}
	archivePath, err := impl.Export(opts)
	testutil.RequireNoError(t, err)
	testutil.RequireTrue(t, archivePath != "", "export must succeed even when vault is locked")
}

// TST-CORE-734
func TestPortability_23_1_11_DatabaseWritesResumedAfterExport(t *testing.T) {
	// After export completes, WAL writes must resume with no data loss.
	var impl testutil.ExportManager
	testutil.RequireImplementation(t, impl, "ExportManager")

	dir := testutil.TempDir(t)
	opts := testutil.ExportOptions{
		Passphrase: testutil.TestPassphrase,
		DestPath:   dir,
	}
	_, err := impl.Export(opts)
	testutil.RequireNoError(t, err)
	// Write resumption is verified at integration level —
	// ensure no errors post-export when storing new vault items.
}

// --------------------------------------------------------------------------
// §23.2 Import Process (12 scenarios)
// --------------------------------------------------------------------------

// TST-CORE-735
func TestPortability_23_2_1_ImportPromptsForPassphrase(t *testing.T) {
	// `dina import` prompts for passphrase, derives key via Argon2id, decrypts archive.
	var impl testutil.ImportManager
	testutil.RequireImplementation(t, impl, "ImportManager")

	opts := testutil.ImportOptions{
		ArchivePath: "/tmp/dina-test-archive.dina",
		Passphrase:  testutil.TestPassphrase,
	}
	_, err := impl.Import(opts)
	// May fail if archive doesn't exist — contract test verifies the API shape.
	_ = err
}

// TST-CORE-736
func TestPortability_23_2_2_ImportWithWrongPassphrase(t *testing.T) {
	// Incorrect passphrase must cause AES-256-GCM decryption failure, import aborted.
	var impl testutil.ImportManager
	testutil.RequireImplementation(t, impl, "ImportManager")

	opts := testutil.ImportOptions{
		ArchivePath: "/tmp/dina-test-archive.dina",
		Passphrase:  testutil.TestPassphraseWrong,
	}
	_, err := impl.Import(opts)
	testutil.RequireError(t, err)
}

// TST-CORE-737
func TestPortability_23_2_3_ImportVerifiesChecksums(t *testing.T) {
	// manifest.json checksums must be verified against restored files.
	var impl testutil.ImportManager
	testutil.RequireImplementation(t, impl, "ImportManager")

	err := impl.VerifyArchive("/tmp/dina-test-archive.dina", testutil.TestPassphrase)
	// Contract test — verifies the verify method exists and can be called.
	_ = err
}

// TST-CORE-738
func TestPortability_23_2_4_ImportDetectsCorruption(t *testing.T) {
	// Corrupted archive (flipped bits) must cause checksum mismatch, import aborted.
	var impl testutil.ImportManager
	testutil.RequireImplementation(t, impl, "ImportManager")

	err := impl.VerifyArchive("/tmp/corrupted-archive.dina", testutil.TestPassphrase)
	testutil.RequireError(t, err)
}

// TST-CORE-739
func TestPortability_23_2_5_ImportChecksVersionCompatibility(t *testing.T) {
	// Archive from incompatible version must be rejected.
	var impl testutil.ImportManager
	testutil.RequireImplementation(t, impl, "ImportManager")

	err := impl.CheckCompatibility("/tmp/incompatible-archive.dina")
	testutil.RequireError(t, err)
}

// TST-CORE-740
func TestPortability_23_2_6_ImportRunsIntegrityCheck(t *testing.T) {
	// After restoring .sqlite files, PRAGMA integrity_check must pass on each database.
	var impl testutil.ImportManager
	testutil.RequireImplementation(t, impl, "ImportManager")

	opts := testutil.ImportOptions{
		ArchivePath: "/tmp/dina-test-archive.dina",
		Passphrase:  testutil.TestPassphrase,
	}
	result, err := impl.Import(opts)
	if err == nil {
		testutil.RequireTrue(t, result.FilesRestored > 0, "import must restore files")
	}
}

// TST-CORE-741
func TestPortability_23_2_7_ImportIntegrityCheckFailure(t *testing.T) {
	// Archive with corrupted .sqlite must fail integrity_check, import aborted, files cleaned up.
	var impl testutil.ImportManager
	testutil.RequireImplementation(t, impl, "ImportManager")

	opts := testutil.ImportOptions{
		ArchivePath: "/tmp/corrupted-sqlite-archive.dina",
		Passphrase:  testutil.TestPassphrase,
	}
	_, err := impl.Import(opts)
	testutil.RequireError(t, err)
}

// TST-CORE-742
func TestPortability_23_2_8_ImportPromptsForRepairing(t *testing.T) {
	// After successful import, user must be notified to re-pair devices and re-configure OpenClaw.
	var impl testutil.ImportManager
	testutil.RequireImplementation(t, impl, "ImportManager")

	opts := testutil.ImportOptions{
		ArchivePath: "/tmp/dina-test-archive.dina",
		Passphrase:  testutil.TestPassphrase,
	}
	result, err := impl.Import(opts)
	if err == nil {
		testutil.RequireTrue(t, result.RequiresRepair, "import must indicate re-pairing is needed")
	}
}

// TST-CORE-743
func TestPortability_23_2_9_ImportedDIDMatchesOriginal(t *testing.T) {
	// DID pre-export must match DID post-import — identity preserved across migration.
	var impl testutil.ImportManager
	testutil.RequireImplementation(t, impl, "ImportManager")

	opts := testutil.ImportOptions{
		ArchivePath: "/tmp/dina-test-archive.dina",
		Passphrase:  testutil.TestPassphrase,
	}
	result, err := impl.Import(opts)
	if err == nil {
		testutil.RequireTrue(t, result.DID != "", "imported DID must be non-empty")
		testutil.RequireHasPrefix(t, result.DID, "did:")
	}
}

// TST-CORE-744
func TestPortability_23_2_10_ImportOnFreshInstance(t *testing.T) {
	// Import on fresh instance (no existing data) must result in clean restore.
	var impl testutil.ImportManager
	testutil.RequireImplementation(t, impl, "ImportManager")

	opts := testutil.ImportOptions{
		ArchivePath: "/tmp/dina-test-archive.dina",
		Passphrase:  testutil.TestPassphrase,
	}
	result, err := impl.Import(opts)
	if err == nil {
		testutil.RequireTrue(t, result.FilesRestored > 0, "fresh import must restore files")
		testutil.RequireTrue(t, result.PersonaCount > 0, "fresh import must restore personas")
	}
}

// TST-CORE-745
func TestPortability_23_2_11_ImportOnExistingDataRejected(t *testing.T) {
	// Import when vault is already populated must be rejected unless --force flag is set.
	var impl testutil.ImportManager
	testutil.RequireImplementation(t, impl, "ImportManager")

	opts := testutil.ImportOptions{
		ArchivePath: "/tmp/dina-test-archive.dina",
		Passphrase:  testutil.TestPassphrase,
		Force:       false, // no force
	}
	_, err := impl.Import(opts)
	testutil.RequireError(t, err)
}

// TST-CORE-746
func TestPortability_23_2_12_ImportRejectsTamperedArchive(t *testing.T) {
	// Modified bytes in archive must trigger integrity error, import aborted.
	var impl testutil.ImportManager
	testutil.RequireImplementation(t, impl, "ImportManager")

	err := impl.VerifyArchive("/tmp/tampered-archive.dina", testutil.TestPassphrase)
	testutil.RequireError(t, err)
}

// --------------------------------------------------------------------------
// §23.3 Cross-Host Migration (4 scenarios)
// --------------------------------------------------------------------------

// TST-CORE-747
func TestPortability_23_3_1_ManagedToSelfHostedVPS(t *testing.T) {
	// Export on managed instance, import on VPS — identical functionality, all data accessible.
	var exportMgr testutil.ExportManager
	testutil.RequireImplementation(t, exportMgr, "ExportManager")

	var importMgr testutil.ImportManager
	testutil.RequireImplementation(t, importMgr, "ImportManager")

	// Export from managed instance.
	dir := testutil.TempDir(t)
	opts := testutil.ExportOptions{
		Passphrase: testutil.TestPassphrase,
		DestPath:   dir,
	}
	archivePath, err := exportMgr.Export(opts)
	testutil.RequireNoError(t, err)

	// Import on VPS.
	importOpts := testutil.ImportOptions{
		ArchivePath: archivePath,
		Passphrase:  testutil.TestPassphrase,
	}
	result, err := importMgr.Import(importOpts)
	testutil.RequireNoError(t, err)
	testutil.RequireTrue(t, result.FilesRestored > 0, "migration must restore files")
}

// TST-CORE-748
func TestPortability_23_3_2_RaspberryPiToMacMini(t *testing.T) {
	// Same archive, same command, any hardware — Pi to Mac.
	var exportMgr testutil.ExportManager
	testutil.RequireImplementation(t, exportMgr, "ExportManager")

	var importMgr testutil.ImportManager
	testutil.RequireImplementation(t, importMgr, "ImportManager")

	dir := testutil.TempDir(t)
	opts := testutil.ExportOptions{
		Passphrase: testutil.TestPassphrase,
		DestPath:   dir,
	}
	archivePath, err := exportMgr.Export(opts)
	testutil.RequireNoError(t, err)

	importOpts := testutil.ImportOptions{
		ArchivePath: archivePath,
		Passphrase:  testutil.TestPassphrase,
	}
	result, err := importMgr.Import(importOpts)
	testutil.RequireNoError(t, err)
	testutil.RequireTrue(t, result.FilesRestored > 0, "cross-hardware migration must work")
}

// TST-CORE-749
func TestPortability_23_3_3_SameDockerImageAcrossHostingLevels(t *testing.T) {
	// Build once, deploy to managed/VPS/sovereign — identical startup behavior.
	var exportMgr testutil.ExportManager
	testutil.RequireImplementation(t, exportMgr, "ExportManager")

	var importMgr testutil.ImportManager
	testutil.RequireImplementation(t, importMgr, "ImportManager")

	// Verify export/import produces consistent results regardless of hosting level.
	dir := testutil.TempDir(t)
	opts := testutil.ExportOptions{
		Passphrase: testutil.TestPassphrase,
		DestPath:   dir,
	}
	archivePath, err := exportMgr.Export(opts)
	testutil.RequireNoError(t, err)

	err = importMgr.CheckCompatibility(archivePath)
	testutil.RequireNoError(t, err)
}

// TST-CORE-750
func TestPortability_23_3_4_MigrationPreservesVaultSearch(t *testing.T) {
	// Export with 10K items, import, search — FTS5 + sqlite-vec results identical post-migration.
	var exportMgr testutil.ExportManager
	testutil.RequireImplementation(t, exportMgr, "ExportManager")

	var importMgr testutil.ImportManager
	testutil.RequireImplementation(t, importMgr, "ImportManager")

	dir := testutil.TempDir(t)
	opts := testutil.ExportOptions{
		Passphrase: testutil.TestPassphrase,
		DestPath:   dir,
	}
	archivePath, err := exportMgr.Export(opts)
	testutil.RequireNoError(t, err)

	importOpts := testutil.ImportOptions{
		ArchivePath: archivePath,
		Passphrase:  testutil.TestPassphrase,
	}
	result, err := importMgr.Import(importOpts)
	if err == nil {
		testutil.RequireTrue(t, result.FilesRestored > 0, "migration must preserve searchable data")
	}
}
