package test

import (
	"bytes"
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/rajmohanutopai/dina/core/internal/domain"
	"github.com/rajmohanutopai/dina/core/internal/handler"
	"github.com/rajmohanutopai/dina/core/internal/middleware"
	"github.com/rajmohanutopai/dina/core/test/testutil"
)

// ==========================================================================
// Session Handler — name auto-generation
// Tests that empty session name gets auto-generated as "SName-<timestamp>".
// ==========================================================================

// --- Mock AgentSessionManager ---

type mockSessionManager struct {
	lastStartName string
	startResult   *domain.AgentSession
	startErr      error
}

func (m *mockSessionManager) StartSession(_ context.Context, agentDID, name string) (*domain.AgentSession, error) {
	m.lastStartName = name
	if m.startErr != nil {
		return nil, m.startErr
	}
	if m.startResult != nil {
		return m.startResult, nil
	}
	return &domain.AgentSession{
		ID:       "sess-001",
		Name:     name,
		AgentDID: agentDID,
		Status:   domain.SessionActive,
	}, nil
}

func (m *mockSessionManager) EndSession(_ context.Context, _, _ string) error { return nil }
func (m *mockSessionManager) GetSession(_ context.Context, _, _ string) (*domain.AgentSession, error) {
	return nil, nil
}
func (m *mockSessionManager) ListSessions(_ context.Context, _ string) ([]domain.AgentSession, error) {
	return nil, nil
}
func (m *mockSessionManager) AddGrant(_ context.Context, _, _, _, _ string) error { return nil }
func (m *mockSessionManager) CheckGrant(_ context.Context, _, _ string) (bool, error) {
	return false, nil
}
func (m *mockSessionManager) ExpireStaleSessions(_ context.Context, _ int64) (int, error) {
	return 0, nil
}

// --------------------------------------------------------------------------
// TST-CORE-920: Empty name generates a default starting with "SName-".
// --------------------------------------------------------------------------

// TRACE: {"suite": "CORE", "case": "1272", "section": "01", "sectionName": "Authentication & Authorization", "subsection": "01", "scenario": "01", "title": "Session_EmptyNameAutoGenerated"}
func TestSession_EmptyNameAutoGenerated(t *testing.T) {
	mgr := &mockSessionManager{}
	h := &handler.SessionHandler{Sessions: mgr}

	body, _ := json.Marshal(map[string]string{"name": ""})
	req := httptest.NewRequest("POST", "/v1/session/start", bytes.NewReader(body))
	ctx := context.WithValue(req.Context(), middleware.AgentDIDKey, "did:key:z6MkTestAgent")
	req = req.WithContext(ctx)
	rr := httptest.NewRecorder()

	h.HandleStartSession(rr, req)

	testutil.RequireEqual(t, rr.Code, http.StatusCreated)

	// The name passed to StartSession must begin with "SName-".
	testutil.RequireTrue(t, strings.HasPrefix(mgr.lastStartName, "SName-"),
		"auto-generated name must start with 'SName-', got: "+mgr.lastStartName)

	// Verify response body also has the generated name.
	var resp domain.AgentSession
	json.NewDecoder(rr.Body).Decode(&resp)
	testutil.RequireTrue(t, strings.HasPrefix(resp.Name, "SName-"),
		"response name must start with 'SName-', got: "+resp.Name)
}

// --------------------------------------------------------------------------
// TST-CORE-921: Non-empty name is used as-is.
// --------------------------------------------------------------------------

// TRACE: {"suite": "CORE", "case": "1273", "section": "01", "sectionName": "Authentication & Authorization", "subsection": "02", "scenario": "01", "title": "Session_ExplicitNameUsedAsIs"}
func TestSession_ExplicitNameUsedAsIs(t *testing.T) {
	mgr := &mockSessionManager{}
	h := &handler.SessionHandler{Sessions: mgr}

	body, _ := json.Marshal(map[string]string{"name": "my-research-task"})
	req := httptest.NewRequest("POST", "/v1/session/start", bytes.NewReader(body))
	ctx := context.WithValue(req.Context(), middleware.AgentDIDKey, "did:key:z6MkTestAgent")
	req = req.WithContext(ctx)
	rr := httptest.NewRecorder()

	h.HandleStartSession(rr, req)

	testutil.RequireEqual(t, rr.Code, http.StatusCreated)
	testutil.RequireEqual(t, mgr.lastStartName, "my-research-task")

	var resp domain.AgentSession
	json.NewDecoder(rr.Body).Decode(&resp)
	testutil.RequireEqual(t, resp.Name, "my-research-task")
}
