import type { DrizzleDB } from '@/db/connection.js'
import type { Logger } from '@/shared/utils/logger.js'
import type { Metrics } from '@/shared/utils/metrics.js'

// ── Context ─────────────────────────────────────────────────────────

/** Shared context passed to every record handler */
export interface HandlerContext {
  db: DrizzleDB
  logger: Logger
  metrics: Metrics
}

// ── Record operation ────────────────────────────────────────────────

/** A single record operation from the Jetstream firehose */
export interface RecordOp {
  /** AT Protocol URI (at://did/collection/rkey) */
  uri: string
  /** DID of the record author */
  did: string
  /** Collection NSID (e.g. com.dina.peerlens.attestation) */
  collection: string
  /** Record key within the collection */
  rkey: string
  /** CID of the record (present on create/update) */
  cid?: string
  /** The record data (present on create/update, absent on delete) */
  record?: Record<string, unknown>
  /**
   * Synthetic correlation id (TN-OBS-002 / Plan §13.8). Generated by
   * the dispatcher at the top of `processEvent` so every downstream
   * log line — validation, rate-limit gate, handler write, dirty-flag
   * upsert — can be joined post-hoc by trace. Stored on
   * `attestations.trace_id` for record-level lookup. Optional because
   * the deletion path doesn't generate one (deletes have no row to
   * stamp), and tests sometimes drive handlers directly without the
   * dispatcher.
   */
  traceId?: string
}

// ── Handler interface ───────────────────────────────────────────────

/** Interface that every record handler must implement */
export interface RecordHandler {
  /** Handle a record creation or update */
  handleCreate(ctx: HandlerContext, op: RecordOp): Promise<void>
  /** Handle a record deletion */
  handleDelete(ctx: HandlerContext, op: RecordOp): Promise<void>
}

// ── Handler registry ────────────────────────────────────────────────

import { attestationHandler } from './attestation.js'
import { vouchHandler } from './vouch.js'
import { endorsementHandler } from './endorsement.js'
import { flagHandler } from './flag.js'
import { replyHandler } from './reply.js'
import { reactionHandler } from './reaction.js'
import { reportRecordHandler } from './report-record.js'
import { revocationHandler } from './revocation.js'
import { delegationHandler } from './delegation.js'
import { collectionHandler } from './collection.js'
import { mediaHandler } from './media.js'
import { subjectHandler } from './subject.js'
import { amendmentHandler } from './amendment.js'
import { verificationHandler } from './verification.js'
import { reviewRequestHandler } from './review-request.js'
import { comparisonHandler } from './comparison.js'
import { subjectClaimHandler } from './subject-claim.js'
import { peerlensPolicyHandler } from './peerlens-policy.js'
import { notificationPrefsHandler } from './notification-prefs.js'
import { serviceProfileHandler } from './service-profile.js'

const handlers: Record<string, RecordHandler> = {
  'com.dina.peerlens.attestation': attestationHandler,
  'com.dina.peerlens.vouch': vouchHandler,
  'com.dina.peerlens.endorsement': endorsementHandler,
  'com.dina.peerlens.flag': flagHandler,
  'com.dina.peerlens.reply': replyHandler,
  'com.dina.peerlens.reaction': reactionHandler,
  'com.dina.peerlens.reportRecord': reportRecordHandler,
  'com.dina.peerlens.revocation': revocationHandler,
  'com.dina.peerlens.delegation': delegationHandler,
  'com.dina.peerlens.collection': collectionHandler,
  'com.dina.peerlens.media': mediaHandler,
  'com.dina.peerlens.subject': subjectHandler,
  'com.dina.peerlens.amendment': amendmentHandler,
  'com.dina.peerlens.verification': verificationHandler,
  'com.dina.peerlens.reviewRequest': reviewRequestHandler,
  'com.dina.peerlens.comparison': comparisonHandler,
  'com.dina.peerlens.subjectClaim': subjectClaimHandler,
  'com.dina.peerlens.trustPolicy': peerlensPolicyHandler,
  'com.dina.peerlens.notificationPrefs': notificationPrefsHandler,
  'com.dina.service.profile': serviceProfileHandler,
}

/**
 * Look up the handler for a collection NSID.
 * Returns null if no handler is registered (unknown collection).
 */
export function routeHandler(collection: string): RecordHandler | null {
  return handlers[collection] ?? null
}

/**
 * Get all registered collection NSIDs.
 */
export function getRegisteredCollections(): string[] {
  return Object.keys(handlers)
}
