"""Write the .env configuration file.

Generates or backfills the .env file with all required Dina configuration.
Idempotent — safe to call on re-runs.
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from pathlib import Path

from scripts.installer.models import InstallerConfig


def write_env(
    config: InstallerConfig,
    session_id: str,
    core_port: int,
    pds_port: int,
    pds_secrets: dict[str, str],
) -> Path:
    """Write the .env file from scratch. Returns the path.

    Only called for first-time install (no existing .env).
    """
    env_file = config.dina_dir / ".env"
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines = [
        "# Dina Home Node Configuration",
        f"# Generated by installer — {now}",
        "#",
        "# Identity seed is encrypted in secrets/wrapped_seed.bin (not stored here).",
        "",
        f"# Session ID — scopes container names and Docker resources.",
        f"DINA_SESSION={session_id}",
        f"COMPOSE_PROJECT_NAME=dina-{session_id}",
        "",
        "# Host ports",
        f"DINA_CORE_PORT={core_port}",
        f"DINA_PDS_PORT={pds_port}",
        "",
        "# AT Protocol PDS secrets (auto-generated, do not edit)",
        f"DINA_PDS_JWT_SECRET={pds_secrets['jwt_secret']}",
        f"DINA_PDS_ADMIN_PASSWORD={pds_secrets['admin_password']}",
        f"DINA_PDS_ROTATION_KEY_HEX={pds_secrets['rotation_key_hex']}",
    ]

    # Owner name
    if config.owner_name:
        lines += ["", "# Owner", f"DINA_OWNER_NAME={config.owner_name}"]

    # LLM providers
    if config.llm_providers:
        lines += ["", "# LLM providers"]
        for provider in config.llm_providers:
            lines.append(f"{provider.env_key}={provider.env_value}")

    # Telegram
    if config.telegram:
        lines += ["", "# Telegram"]
        lines.append(f"DINA_TELEGRAM_TOKEN={config.telegram.token}")
        if config.telegram.user_id:
            lines.append(
                f"DINA_TELEGRAM_ALLOWED_USERS={config.telegram.user_id}"
            )

    lines += [
        "",
        "# Add more providers: see models.json or run ./dina-admin model list",
        "",
    ]

    content = "\n".join(lines)

    # Write with restricted permissions
    fd = os.open(str(env_file), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    try:
        os.write(fd, content.encode("utf-8"))
    finally:
        os.close(fd)

    return env_file


def backfill_env(
    env_file: Path,
    session_id: str,
    core_port: int,
    pds_port: int,
    pds_secrets: dict[str, str],
) -> None:
    """Backfill missing required keys in an existing .env file.

    Does not overwrite existing values. Only adds missing keys.
    """
    content = env_file.read_text()
    additions: list[str] = []

    required = {
        "DINA_SESSION": session_id,
        "COMPOSE_PROJECT_NAME": f"dina-{session_id}",
        "DINA_CORE_PORT": str(core_port),
        "DINA_PDS_PORT": str(pds_port),
        "DINA_PDS_JWT_SECRET": pds_secrets["jwt_secret"],
        "DINA_PDS_ADMIN_PASSWORD": pds_secrets["admin_password"],
        "DINA_PDS_ROTATION_KEY_HEX": pds_secrets["rotation_key_hex"],
    }

    for key, value in required.items():
        if f"{key}=" not in content:
            additions.append(f"{key}={value}")

    if additions:
        with open(env_file, "a") as f:
            f.write("\n# Backfilled by installer\n")
            for line in additions:
                f.write(f"{line}\n")
