/**
 * Pure envelope constructors — the deterministic "build a correct wire
 * shape from these inputs" functions, extracted from `@dina/core` so
 * third-party Dina implementations can reuse them.
 *
 * **Zero runtime deps.** No crypto, no base64, no random. Callers
 * provide pre-encoded / pre-minted values (body bytes base64'd by the
 * caller, `requestId` generated by the caller). Core + brain keep
 * thin wrappers that inject those platform-specific bits.
 *
 * Source: docs/HOME_NODE_LITE_TASKS.md Phase 1b task 1.19.
 *
 * Historical parity note: `buildMessageJSON`'s key order
 * (id, type, from, to, created_time, body) matches Go's
 * declaration-order `json.Marshal` of `DinaMessage`. Changing it
 * breaks cross-runtime Ed25519 signature verification — signatures
 * are computed over the JSON bytes these builders emit.
 */

import { RPC_REQUEST_TYPE } from './constants';
import type { CoreRPCRequest } from './types/core_rpc';

// ---------------------------------------------------------------------------
// DinaMessage envelope
// ---------------------------------------------------------------------------

/**
 * Input shape for `buildMessageJSON`. Matches the DinaMessage fields
 * that serialise onto the wire; `bodyBase64` is pre-encoded because
 * protocol carries no base64 runtime.
 */
export interface BuildMessageJSONInput {
  id: string;
  type: string;
  from: string;
  /** Single recipient or an array — protocol normalises to array. */
  to: string | string[];
  /** Unix seconds (matches wire). */
  created_time: number;
  /** Body bytes, already base64-encoded by the caller. */
  bodyBase64: string;
}

/**
 * Assemble the canonical JSON string for a DinaMessage. The signer
 * signs these exact bytes; the receiver reconstructs them for
 * verification. Determinism is load-bearing: key order is fixed
 * (Go-interop), `to` is always an array on the wire (even when the
 * caller passed a bare string).
 */
export function buildMessageJSON(msg: BuildMessageJSONInput): string {
  return JSON.stringify({
    id: msg.id,
    type: msg.type,
    from: msg.from,
    to: Array.isArray(msg.to) ? msg.to : [msg.to],
    created_time: msg.created_time,
    body: msg.bodyBase64,
  });
}

// ---------------------------------------------------------------------------
// Core RPC envelope
// ---------------------------------------------------------------------------

export interface BuildRPCRequestInput {
  /** Caller-minted unique id, typically `rpc-<hex(random_8_bytes)>`. */
  requestId: string;
  method: string;
  path: string;
  query: string;
  body: string;
  headers: Record<string, string>;
  senderDID: string;
}

/**
 * Assemble a `CoreRPCRequest` envelope. Pure — no random, no crypto.
 * Core's wrapper in `relay/rpc_envelope.ts` mints `requestId` via
 * `bytesToHex(randomBytes(8))` then calls through.
 */
export function buildRPCRequest(input: BuildRPCRequestInput): CoreRPCRequest {
  return {
    type: RPC_REQUEST_TYPE,
    request_id: input.requestId,
    from: input.senderDID,
    method: input.method,
    path: input.path,
    query: input.query,
    headers: input.headers,
    body: input.body,
  };
}
