export const CONSTANTS = {
  // Scoring weights
  SENTIMENT_WEIGHT: 0.40,
  VOUCH_WEIGHT: 0.25,
  REVIEWER_WEIGHT: 0.20,
  NETWORK_WEIGHT: 0.15,

  // Scoring multipliers
  SENTIMENT_HALFLIFE_DAYS: 180,
  EVIDENCE_MULTIPLIER: 1.3,
  VERIFIED_MULTIPLIER: 1.5,
  BILATERAL_MULTIPLIER: 1.4,

  // Graph
  MAX_GRAPH_DEPTH: 2,
  MAX_GRAPH_NODES_RESPONSE: 500,
  MAX_EDGES_PER_HOP: 500,
  GRAPH_QUERY_TIMEOUT_MS: 100,

  // Pagination
  DEFAULT_PAGE_SIZE: 25,
  MAX_PAGE_SIZE: 100,

  // Tombstones
  COORDINATION_TOMBSTONE_THRESHOLD: 3,

  // Vouch strength thresholds
  VOUCH_LIGHTLY: 1,
  VOUCH_WELL: 3,
  VOUCH_STRONGLY: 10,

  // ISR revalidation (seconds)
  SUBJECT_PAGE_REVALIDATE_S: 60,
  PROFILE_PAGE_REVALIDATE_S: 120,
  SEARCH_PAGE_REVALIDATE_S: 30,

  // Scorer
  SYBIL_MIN_CLUSTER_SIZE: 3,
  COORDINATION_WINDOW_HOURS: 48,

  // Rate limiter
  MAX_RECORDS_PER_HOUR: 50,
  MAX_TRACKED_DIDS: 100_000,

  // Bounded queue
  MAX_QUEUE_SIZE: 1000,
  MAX_CONCURRENCY: 20,

  // Cursor
  CURSOR_SAVE_INTERVAL: 100,

  // Subject resolution
  MAX_CHAIN_DEPTH: 5,

  // Scorer batch
  SCORER_BATCH_SIZE: 5000,

  // Trust edge weights
  EDGE_WEIGHT_VOUCH_HIGH: 1.0,
  EDGE_WEIGHT_VOUCH_MODERATE: 0.6,
  EDGE_WEIGHT_VOUCH_LOW: 0.3,
  EDGE_WEIGHT_ENDORSEMENT_WORKED: 0.8,
  EDGE_WEIGHT_ENDORSEMENT_OBSERVED: 0.4,
  EDGE_WEIGHT_DELEGATION: 0.9,
  EDGE_WEIGHT_COSIGN: 0.7,
  EDGE_WEIGHT_POSITIVE_ATTESTATION: 0.3,

  // Damping
  DAMPING_FACTOR: 0.85,
  BASE_SCORE: 0.1,

  // Cache
  MAX_CACHE_SIZE: 10_000,
  CACHE_TTL_RESOLVE: 5_000,
  CACHE_TTL_GET_PROFILE: 10_000,
  CACHE_TTL_SEARCH: 3_000,

  // Reconnection
  MAX_RECONNECT_DELAY_MS: 60_000,
} as const
