/** All trust record collection NSIDs */
export const TRUST_COLLECTIONS = [
  'com.dinakernel.peerlens.attestation',
  'com.dinakernel.peerlens.vouch',
  'com.dinakernel.peerlens.endorsement',
  'com.dinakernel.peerlens.flag',
  'com.dinakernel.peerlens.reply',
  'com.dinakernel.peerlens.reaction',
  'com.dinakernel.peerlens.reportRecord',
  'com.dinakernel.peerlens.revocation',
  'com.dinakernel.peerlens.delegation',
  'com.dinakernel.peerlens.collection',
  'com.dinakernel.peerlens.media',
  'com.dinakernel.peerlens.subject',
  'com.dinakernel.peerlens.amendment',
  'com.dinakernel.peerlens.verification',
  'com.dinakernel.peerlens.reviewRequest',
  'com.dinakernel.peerlens.comparison',
  'com.dinakernel.peerlens.subjectClaim',
  'com.dinakernel.peerlens.trustPolicy',
  'com.dinakernel.peerlens.notificationPrefs',
  'com.dinakernel.service.profile',
  'com.dinakernel.commerce.catalog',
  'com.dinakernel.commerce.catalogSnapshot',
  'com.dinakernel.commerce.relationshipClaim',
] as const

export type TrustCollection = typeof TRUST_COLLECTIONS[number]

/** Map from short record type name to full collection NSID */
export const COLLECTION_NSID_MAP: Record<string, TrustCollection> = {
  attestation: 'com.dinakernel.peerlens.attestation',
  vouch: 'com.dinakernel.peerlens.vouch',
  endorsement: 'com.dinakernel.peerlens.endorsement',
  flag: 'com.dinakernel.peerlens.flag',
  reply: 'com.dinakernel.peerlens.reply',
  reaction: 'com.dinakernel.peerlens.reaction',
  reportRecord: 'com.dinakernel.peerlens.reportRecord',
  revocation: 'com.dinakernel.peerlens.revocation',
  delegation: 'com.dinakernel.peerlens.delegation',
  collection: 'com.dinakernel.peerlens.collection',
  media: 'com.dinakernel.peerlens.media',
  subject: 'com.dinakernel.peerlens.subject',
  amendment: 'com.dinakernel.peerlens.amendment',
  verification: 'com.dinakernel.peerlens.verification',
  reviewRequest: 'com.dinakernel.peerlens.reviewRequest',
  comparison: 'com.dinakernel.peerlens.comparison',
  subjectClaim: 'com.dinakernel.peerlens.subjectClaim',
  trustPolicy: 'com.dinakernel.peerlens.trustPolicy',
  notificationPrefs: 'com.dinakernel.peerlens.notificationPrefs',
  serviceProfile: 'com.dinakernel.service.profile',
  commerceCatalog: 'com.dinakernel.commerce.catalog',
  commerceCatalogSnapshot: 'com.dinakernel.commerce.catalogSnapshot',
  commerceRelationshipClaim: 'com.dinakernel.commerce.relationshipClaim',
}
