#!/usr/bin/env python3
"""One-time setup: record test actor DIDs from a running test stack.

Run this ONCE after the first `prepare_non_unit_env.sh up`. It reads
each Core's real PLC-registered DID and writes them to the permanent
fixture file tests/fixtures/test_actors.json.

Usage:
    # First time only (stack must be running):
    python scripts/setup_test_actors.py

    # Verify:
    cat tests/fixtures/test_actors.json
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# Allow import from project root
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tests.shared.test_stack import TestStackServices

FIXTURE_PATH = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "test_actors.json"

ACTORS = {
    "alonso": {
        "seed": "0101010101010101010101010101010101010101010101010101010101010101",
        "handle": "alonso.test",
        "display_name": "Don Alonso",
    },
    "sancho": {
        "seed": "0202020202020202020202020202020202020202020202020202020202020202",
        "handle": "sancho.test",
        "display_name": "Sancho",
    },
    "chairmaker": {
        "seed": "0303030303030303030303030303030303030303030303030303030303030303",
        "handle": "chairmaker.test",
        "display_name": "ChairMaker",
    },
    "albert": {
        "seed": "0404040404040404040404040404040404040404040404040404040404040404",
        "handle": "albert.test",
        "display_name": "Albert",
    },
}


def main() -> None:
    print("Reading DIDs from running test stack...")
    ts = TestStackServices()
    ts.assert_ready()

    fixture: dict = {"_comment": "Auto-generated by scripts/setup_test_actors.py. Do not edit.", "actors": {}}

    for name, meta in ACTORS.items():
        did = ts.actor_did(name, retries=10, delay=2)
        fixture["actors"][name] = {
            "did": did,
            "seed": meta["seed"],
            "handle": meta["handle"],
            "display_name": meta["display_name"],
            "core_port": int(ts.core_url(name).split(":")[-1]),
            "brain_port": int(ts.brain_url(name).split(":")[-1]),
        }
        print(f"  {name}: {did}")

    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE_PATH.write_text(json.dumps(fixture, indent=2) + "\n")
    print(f"\nSaved to {FIXTURE_PATH}")
    print("This file is committed to the repo and never changes unless seeds change.")


if __name__ == "__main__":
    main()
