import { pgTable, text, timestamp, boolean, jsonb, index } from 'drizzle-orm/pg-core'
import { subjects } from './subjects'

export const attestations = pgTable('attestations', {
  uri: text('uri').primaryKey(),
  authorDid: text('author_did').notNull(),
  cid: text('cid').notNull(),
  subjectId: text('subject_id').references(() => subjects.id),
  subjectRefRaw: jsonb('subject_ref_raw').notNull(),
  category: text('category').notNull(),
  sentiment: text('sentiment').notNull(),
  domain: text('domain'),
  confidence: text('confidence'),
  isAgentGenerated: boolean('is_agent_generated').default(false),
  hasCosignature: boolean('has_cosignature').default(false),
  cosignerDid: text('cosigner_did'),
  dimensionsJson: jsonb('dimensions_json'),
  interactionContextJson: jsonb('interaction_context_json'),
  contentContextJson: jsonb('content_context_json'),
  productContextJson: jsonb('product_context_json'),
  evidenceJson: jsonb('evidence_json'),
  mentionsJson: jsonb('mentions_json'),
  relatedAttestationsJson: jsonb('related_attestations_json'),
  bilateralReviewJson: jsonb('bilateral_review_json'),
  tags: text('tags').array(),
  text: text('text'),
  searchContent: text('search_content'),
  recordCreatedAt: timestamp('record_created_at').notNull(),
  indexedAt: timestamp('indexed_at').notNull().defaultNow(),
  isRevoked: boolean('is_revoked').default(false),
  revokedByUri: text('revoked_by_uri'),
  isAmended: boolean('is_amended').default(false),
  latestAmendmentUri: text('latest_amendment_uri'),
}, (table) => [
  index('attestations_author_idx').on(table.authorDid),
  index('attestations_subject_idx').on(table.subjectId),
  index('attestations_sentiment_idx').on(table.sentiment),
  index('attestations_domain_idx').on(table.domain),
  index('attestations_category_idx').on(table.category),
  index('attestations_created_idx').on(table.recordCreatedAt),
  index('attestations_tags_idx').using('gin', table.tags),
  index('attestations_cosigner_idx').on(table.cosignerDid),
  index('attestations_subject_sentiment_idx').on(table.subjectId, table.sentiment),
  index('attestations_author_domain_idx').on(table.authorDid, table.domain),
])
