/**
 * Per-category recency-decay tuning (TN-V2-RANK-006).
 *
 * The trust scorer's sentiment component weights each attestation
 * by an exponential recency factor — `exp(-ageDays / halflife)`.
 * V1 used a single 180-day half-life for everything, which is too
 * aggressive for slow-moving categories (a great novel from 2010
 * is still a great novel) and too forgiving for fast-moving ones
 * (a 4-year-old phone review is largely obsolete).
 *
 * V2 picks a half-life based on the attestation's `category`:
 *   - **Tech** (~6 months): phones, laptops, software, IDEs.
 *     Specs change yearly; today's flagship is tomorrow's mid-tier.
 *   - **Restaurants** (~1 year): chefs change, menus rotate, but
 *     a place's character has medium persistence.
 *   - **Books** (~5 years): a good book stays good. The slowest
 *     decay because the underlying object literally doesn't change.
 *   - **Services** (~1.5 years): hairdressers, dentists, lawyers.
 *     Quality can drift with personnel changes — slower than tech,
 *     faster than books.
 *   - **Default** (180 days): unmatched categories keep the V1
 *     baseline. The default exists so an exotic category doesn't
 *     produce 0/Infinity weights.
 *
 * **Lookup strategy** is exact-match-first, then progressively
 * longer prefix shrinks. For `'product:phone:samsung'`:
 *   1. `'product:phone:samsung'` — exact, no match
 *   2. `'product:phone'` — prefix, match → tech half-life
 *   3. `'product'` — would match if defined; for now falls to default
 * This lets curators add increasingly specific overrides without
 * touching upstream rules.
 *
 * **Hot-reload via `appview_config`** (deferred): the spec calls for
 * `Configurable in appview_config`. The current implementation pins
 * the table in code because there's no DB-backed config surface for
 * recency yet — the existing `trust_v1_params` table is keyed
 * (string, number) and doesn't carry per-category mappings cleanly.
 * When a config schema lands (V3 admin surface), the lookup function
 * here gets a DB-merge layer the same way `trust-v1-params-reader`
 * works today. The function signature already accepts an optional
 * override map so callers can inject params from a future config.
 *
 * Pure function. Same input always returns the same output.
 */

import { CONSTANTS } from '@/config/constants.js'

/**
 * Built-in category → half-life-days mapping. Curator-edited; not
 * autogenerated. Keys are lowercase category strings; values are
 * positive integers in days. The map is deliberately small — every
 * entry needs a domain rationale, not "we should add more rows."
 */
export const DEFAULT_CATEGORY_HALFLIFE_DAYS: ReadonlyMap<string, number> = new Map([
  // Tech — fast-moving. Specs evolve in months, not years.
  ['product:phone', 180],
  ['product:laptop', 180],
  ['product:tech', 180],
  ['product:software', 180],
  ['product:ide', 180],
  // Books — slow-moving. The artefact itself doesn't change.
  ['product:book', 1825],   // 5 years
  // Restaurants / hospitality — medium decay.
  ['place:restaurant', 365],
  ['place:cafe', 365],
  ['place:bar', 365],
  ['place:hotel', 730],     // 2 years — chains shift slower than indie spots
  // Services — slower than tech, faster than books.
  ['service', 540],         // 1.5 years
])

/**
 * Fallback half-life for any category not in
 * `DEFAULT_CATEGORY_HALFLIFE_DAYS` and not in a caller-supplied
 * override. Sourced from `CONSTANTS.SENTIMENT_HALFLIFE_DAYS` so a
 * future global tuning change updates both V1 callers (any path
 * that doesn't pass `category`) and V2 fallback in one place — no
 * risk of the two values drifting apart.
 */
export const DEFAULT_HALFLIFE_DAYS = CONSTANTS.SENTIMENT_HALFLIFE_DAYS

/**
 * Resolve a half-life (in days) for a given attestation `category`.
 * Returns a positive integer.
 *
 * **Lookup walk** (single pass, more-specific-wins):
 * Walk the colon-separated segments from full length down to one
 * segment. At each level, check the override map first, then the
 * built-in `DEFAULT_CATEGORY_HALFLIFE_DAYS`. First match wins.
 *
 * For `'product:phone:samsung'` the walk visits:
 *   1. `'product:phone:samsung'` — override? default?
 *   2. `'product:phone'` — override? default?  ← matches built-in (180)
 *   3. `'product'` — would match if defined
 *
 * Consequence: a deeper-matching built-in entry beats a shallower
 * override (the curator can't override a less-specific level to
 * affect a more-specific category — they need to add the override
 * at the same depth as the existing built-in entry).
 *
 * `category` of empty string / null / undefined returns
 * `DEFAULT_HALFLIFE_DAYS` — the scorer treats "no category" as "no
 * specific decay signal" rather than crashing.
 *
 * Override values that are not positive (`0` or negative) are
 * skipped silently — they would otherwise produce `exp(-x/0) = NaN`
 * or `exp(-x/-N) = ∞` downstream.
 */
export function halflifeForCategory(
  category: string | null | undefined,
  override?: ReadonlyMap<string, number>,
): number {
  if (typeof category !== 'string' || category.length === 0) {
    return DEFAULT_HALFLIFE_DAYS
  }
  const lowered = category.toLowerCase()
  // Walk from full string down to single segment, checking override
  // first then default at each level. This means a 2-segment override
  // for `'product:phone'` beats a 1-segment default for `'product'`,
  // matching "more specific wins" intuition.
  const segments = lowered.split(':')
  for (let i = segments.length; i > 0; i--) {
    const key = segments.slice(0, i).join(':')
    const overrideHit = override?.get(key)
    if (overrideHit !== undefined && overrideHit > 0) return overrideHit
    const defaultHit = DEFAULT_CATEGORY_HALFLIFE_DAYS.get(key)
    if (defaultHit !== undefined) return defaultHit
  }
  return DEFAULT_HALFLIFE_DAYS
}
